### ISSUE TITLE
Script execution timed out

### ISSUE THREAD

**Issue by MissXecutioner** [SpirTBBX/Folder-Downloader-And-Precacher#2]
Hello, I am getting this error while the plugin is running, how can we solve it?

> L 08/27/2023 - 00:53:45: [SM] Exception reported: Script execution timed out
> L 08/27/2023 - 00:53:45: [SM] Blaming: spirt_folder_dl_precache.smx
> L 08/27/2023 - 00:53:45: [SM] Call stack trace:
> L 08/27/2023 - 00:53:45: [SM]   [1] Line 118, D:\Desktop\Projetos CSGO\Plugins\Alliedmods\Folder Downloader And Precacher (1.1.1)\addons\sourcemod\scripting\spirt_folder_dl_precache.sp::LookPathType
> L 08/27/2023 - 00:53:45: [SM]   [2] Line 118, D:\Desktop\Projetos CSGO\Plugins\Alliedmods\Folder Downloader And Precacher (1.1.1)\addons\sourcemod\scripting\spirt_folder_dl_precache.sp::LookPathType
> L 08/27/2023 - 00:53:45: [SM]   [3] Line 118, D:\Desktop\Projetos CSGO\Plugins\Alliedmods\Folder Downloader And Precacher (1.1.1)\addons\sourcemod\scripting\spirt_folder_dl_precache.sp::LookPathType
> L 08/27/2023 - 00:53:45: [SM]   [4] Line 76, D:\Desktop\Projetos CSGO\Plugins\Alliedmods\Folder Downloader And Precacher (1.1.1)\addons\sourcemod\scripting\spirt_folder_dl_precache.sp::FolderLoop
> L 08/27/2023 - 00:53:45: [SM]   [5] Line 60, D:\Desktop\Projetos CSGO\Plugins\Alliedmods\Folder Downloader And Precacher (1.1.1)\addons\sourcemod\scripting\spirt_folder_dl_precache.sp::OnConfigsExecuted

**Comment by SpirTBBX** [comment]
Sorry for the late response, I had a busy day and only had an opportunity to answer now. Thanks for the call stack trace and for the report.

Could you please provide as well your configuration file, if possible?
The reason I want it is the following: sometimes, people add like `models/myfolder` and then they have another line like `models/myfolder/another_sub_folder`. What will happen is that the plugin will take more time to do stuff (and will execute the same thing two or more times). Try to have your config file as generic as possible.

My servers run the following configutation:
```
models
materials
sound
panorama/OUR_CUSTOM_FOLDER
```

For context: by default, if a function takes more than 30 seconds, iirc, it will unload the plugin to avoid your server to possibly crash.

Does the server take to long to load the map / hang your game client as "Connecting to server..."? Whenever this error happens? Does it happen everytime? Do you have precache enabled?

PS: If you run on slow hardware / have slow disks this can happen quite frequently.

I will look it up and try to optimize it and publish a new version. Expect a new version in the following days. I will message you out here once the new version has been released.

Best Regards.

**Comment by MissXecutioner** [comment]
```sourcepawn
folders.txt
-----------
models
materials
sound
``` 
Due to too many operations during the precache process, Script execution gives timed out error and crashes the server.

**Comment by SpirTBBX** [comment]
I would advise getting rid of the precache unless you really need it. Usually plugins will precache the models or sounds whenever they're required. Disabling precache will fix you issue most likely. Give it a try
